language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: KhWht07YDpC0PGJFIIN8bh9FyZb1c0QFsXSsXK4P5GCW0NXOZVWf4/sxEYi1BlOoYbXNrlKv+TyDfywfx21gLW3APXahsx7IzLyoM+xLqNxzHBrMN10d/k6+SsWW5nG9oIptHiDCG8JXpH5Kc8UFiphltaV4+PlZBfGmIdYU+kuawmwkjkadqL1hCWwap3gkAGb7u4Epez5lVKJBZLxu52G3EjZ1Pl4pgbYTNw/NPDHHWrRWmQXOdR7b5pzgopjKRbGc916mVpoimAgQUN73OxWOOkaXHoUlKMISZT1AbLBAlpQ8cVSvjZqkTFa/Oj/Q8cDwfi4fcYEtr5mkgn67POBfV9qfKh2mMihzAz8RPrglDx0b4JSfa1wcGZGDcaN3hiyJVxe3sLmfwg1xLRsvPo4ynnnPAxnZqH4acNLr/9Bsti4cVVy8PNoVqsYwYf5loFBad5fJgVSRK/Ua5vVp3kRqwP55DOxk13YAayGYep+q8yx/0b9LxA0OLxLqTUFVVtmHdEZg6673hiezb8xIf95lkHArjqCP02/u4gL8Av0AT6J/niDvASW17KV7xNY1T/MwcKwB92NWk+Csd7PWEWx04Nbu3RM6l3Dr/oro8ILxrjsKUHjYM+bJ/IfOos5rJ+72ZpaGduxY/ozyhyB4OWcK7LVsDlQBPMYILKstspg=
    app: rocky-citadel-93498
  on:
    repo: HurricanePete/node-shopping-list-integration-tests
