language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: X9K52fykUn92f7js7awPwVJp6If3uvtz15V7j8bmjm9UrSMj4+/dzzHsSZ9U1Tpp0KhfdkIz3MUSawvWd2q5DBcayqaVpmYyc4Yp8jQslFcTy13H8iWD99nTTeaWDwPJFhPFIIVqjBmf8JUdeVIehwO8c7nF315amVA6Yv3ithv6pIJcm7xPO4HcGMG0K37YFUWwF6rr55ebqydwkthT5ThFi85ASM1fF4xF7Z2A+GV9ERMsdiNan1b990k9xCcq5LHS5YtL1stjffOPFUPLARaJKaxdlAj2pn44Y8/R9uVAPBe0G76p9do4ZgP3M9/lhYkBuavnBfuzQXzXhqA28UgWVuTkPPwyA3UP12hpa1vvrOfepQYb4kE6uWRoGDCJQkwokaYxrsDXzcjnVV2I+6I05AY4jsnDTsvVhn0javPHah+vKmECQn/WDB22EeLBmpVn03EK2IPdaCnStwBXjprGGFB4t+ROu+/7ma96p3kRdCCoHs+zwo76WKh2U6g4Qag7hAukPNmiWW3pKz3iH/O3bNcXSUZBo6IoNPVOu8SBKzCJaqPOqktI7l4yWWi7sLP4f7+nPpNXeuQBHusmDz5yZGWWmBTWVHUrVFFxXC4a+1pk7cuwIh9/iOWP0d1vv0GgXvGsnTyoAnn1zZKLPr2Q9iil0pn4TFvI1ZGdwhw=
  app: fast-ocean-96339