language: node_js
node_js: node
deploy:
  app: rocky-citadel-93498
  api_key:
    secure: a7DODO5LXildCbw13ZbpWntK81amQRKAArkNGyyvlv2ToihduYX5NELMsIydy2rBAWsJvRUDRew7W/FmLRjI3pBHrVFRFQC/ZB7ACMMxupBfpt62HrqHPQvxiISVKt9+rP/Qa3v9uzQ9VtIgtQx2wh3h71eVHtag6WGOOXPWENhULyIhLt8BqZG3/epg4vt/OTFQfBaydh/cBoImqhfEheghtmWf9tPDaBNEGgmfNHeUlSjLI9lshjHYIxihmrBSgKZjPuri5zkOSULDkBGVmeEgZX+Gyjw868aM6xE7LQ8m5NbVwJtYpTJWERnDwlNNMa3Rrin+R9VXECu1s1n5S2tUfPzeMqdfwDK8YWlR+LS7+fQTUBzgQXIT4SCU5348CuCqSSHgorbbWMXDpXEWcV7UTwnPVwjZjP1+xgJujZDXzh6nDyoFnjdzwACnMms1g/pbUAltR8ZnAu0DdMdAimJlcpvMq9gw7tqZy8d91vkNBeRtX9pIQTtl3cf6kL5vzEP8YqQ0vNdJDTqJ93MM+cB8M0LM4n9c8P9J8m6po01awusAs62sLBg2Y0B4spf0SYOrZsuA6Nr9BV6HekTIJ+hjxPxKQnEoZcqG02JBQVYnkmwoNdPjQCrFqpOMWh5ROqycP3dphvLGADQe53WRPfhsLEfGhZyWvHa0b3Bd0K0=
